export const MILESTONE_CATEGORIES = [
  "Planning",
  "Finance & Land",
  "Builder Selection",
  "Design & Drawings",
  "Preliminary Agreement",
  "Contract Signing",
  "Approvals & Permits",
  "Site Preparation",
  "Earthworks",
  "Slab",
  "Frame",
  "Double Brick",
  "External Walls",
  "Roof",
  "Lockup",
  "Rough-in",
  "Plasterboard & Lining",
  "Fixing Stage",
  "Cabinetry",
  "Tiling",
  "Flooring",
  "Painting",
  "Electrical",
  "Plumbing",
  "Appliances & Fixtures",
  "Interior Design",
  "Landscaping",
  "Practical Completion",
  "Handover",
  "Post-Build Improvements",
] as const;

export type MilestoneCategory = (typeof MILESTONE_CATEGORIES)[number];
